services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  PhpList\Core\Domain\Messaging\Command\:
    resource: '../../src/Domain/Messaging/Command'
    tags: ['console.command']

  PhpList\Core\Domain\Identity\Command\:
    resource: '../../src/Domain/Identity/Command'
    tags: ['console.command']

  PhpList\Core\Domain\Messaging\Command\ProcessBouncesCommand:
    arguments:
      $protocolProcessors: !tagged_iterator 'phplist.bounce_protocol_processor'

  TatevikGr\RssFeedBundle\Command\RssDispatchCommand:
    tags: ['console.command']
