services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  PhpList\Core\Domain\Subscription\Service\ArrayToDtoMapper:
    autowire: true
    autoconfigure: true

  PhpList\Core\Domain\Subscription\Service\CsvToDtoImporter:
    autowire: true
    autoconfigure: true
