services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  PhpList\Core\Bounce\Service\Processor\PopBounceProcessor:
    arguments:
      $host: '%imap_bounce.host%'
      $port: '%imap_bounce.port%'
      $mailboxNames: '%imap_bounce.mailbox_name%'
    tags: ['phplist.bounce_protocol_processor']

  PhpList\Core\Bounce\Service\Processor\MboxBounceProcessor:
    tags: ['phplist.bounce_protocol_processor']

  PhpList\Core\Bounce\Service\Processor\AdvancedBounceRulesProcessor: ~

  PhpList\Core\Bounce\Service\Processor\UnidentifiedBounceReprocessor: ~

  PhpList\Core\Bounce\Service\Processor\BounceDataProcessor: ~
