services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  PhpList\Core\Domain\Messaging\Service\Processor\PopBounceProcessor:
    tags: ['phplist.bounce_protocol_processor']

  PhpList\Core\Domain\Messaging\Service\Processor\MboxBounceProcessor:
    tags: ['phplist.bounce_protocol_processor']
