services:
  PhpList\Core\Domain\Subscription\Service\Provider\SubscriberProvider:
    autowire: true
    autoconfigure: true

  PhpList\Core\Core\ParameterProvider:
    arguments:
      $config: '%app.config%'

  PhpList\Core\Domain\Common\IspRestrictionsProvider:
    autowire: true
    autoconfigure: true
    arguments:
      $confPath: '%app.phplist_isp_conf_path%'

  PhpList\Core\Domain\Subscription\Service\Provider\CheckboxGroupValueProvider: ~
  PhpList\Core\Domain\Subscription\Service\Provider\SelectOrRadioValueProvider: ~
  PhpList\Core\Domain\Subscription\Service\Provider\ScalarValueProvider: ~

  PhpList\Core\Domain\Configuration\Service\Provider\DefaultConfigProvider:
    calls:
      - [ setTranslator, [ '@translator' ] ]

  PhpList\Core\Domain\Configuration\Service\Provider\ConfigProvider:
