language: php

php:
- 7.0
- 7.1
- 7.2

services:
- mysql

env:
  global:
  - PHPLIST_DATABASE_NAME=phplist PHPLIST_DATABASE_USER=travis PHPLIST_DATABASE_PASSWORD=''
  matrix:
  - DEPENDENCIES=latest
  - DEPENDENCIES=oldest

matrix:
  include:
  - php: '7.2'
    env: COVERAGE=yes DEPENDENCIES=latest

notifications:
  slack:
    rooms:
      - SLACKNOTIFICATION
  on_success: change
  on_failure: always

sudo: false

cache:
  directories:
  - vendor
  - "$HOME/.composer/cache"

before_install:
- >
  if [[ $COVERAGE = yes ]]; then
    export PHPUNIT_OPTIONS="--coverage-clover=/tmp/coverage.clover";
  else
    phpenv config-rm xdebug.ini;
  fi;

- >
  echo;
  echo "Creating the database and importing the database schema";
  mysql -e "CREATE DATABASE ${PHPLIST_DATABASE_NAME};";
  mysql -u root -e "GRANT ALL ON ${PHPLIST_DATABASE_NAME}.* TO '${PHPLIST_DATABASE_USER}'@'%';";
  mysql ${PHPLIST_DATABASE_NAME} < Database/Schema.sql;

install:
- >
  echo;
  if [ "$DEPENDENCIES" = "latest" ]; then
    echo "Installing the latest dependencies";
    composer update --with-dependencies --prefer-stable --prefer-dist
  else
    echo "Installing the lowest dependencies";
    composer update --with-dependencies --prefer-stable --prefer-dist --prefer-lowest
  fi;
  composer show;

script:
- >
  echo;
  echo "Validating the composer.json";
  composer validate --no-check-all --no-check-lock --strict;

- >
  echo;
  echo "Linting all PHP files";
  find src/ tests/ public/ -name ''*.php'' -print0 | xargs -0 -n 1 -P 4 php -l; php -l bin/*;

- >
  echo;
  echo "Running PHPUnit tests";
  vendor/bin/phpunit $PHPUNIT_OPTIONS;

- >
  echo;
  echo "Running the static analysis";
  vendor/bin/phpstan analyse -l 5 bin/ src/ tests/ public/;

- >
  echo;
  echo "Running PHPMD";
  vendor/bin/phpmd src/ text Configuration/PHPMD/rules.xml;

- >
  echo;
  echo "Running PHP_CodeSniffer";
  vendor/bin/phpcs --standard=Configuration/PhpCodeSniffer/ bin/ src/ tests/ public/;

after_script:
- >
  if [[ $COVERAGE = yes ]]; then
    wget https://scrutinizer-ci.com/ocular.phar;
    php ocular.phar code-coverage:upload --format=php-clover /tmp/coverage.clover
  fi;
