doctrine_migrations:
    migrations_paths:
        'PhpList\Core\Migrations': '%kernel.project_dir%/src/Migrations'
#        'TatevikGr\RssBundle\RssFeedBundle\Migrations': '%kernel.project_dir%/vendor/tatevikgr/rss-bundle/src/RssFeedBundle/Migrations'
    all_or_nothing: true
    organize_migrations: false
    custom_template: '%kernel.project_dir%/src/Migrations/_template_migration.php.tpl'
    storage:
        table_storage:
            table_name: 'doctrine_migration_versions'
            version_column_name: 'version'
            version_column_length: 191
            executed_at_column_name: 'executed_at'
